### ISSUE TITLE
Cloudflare proxied mode not working

### ISSUE THREAD

**Issue by max-zak** [DzenDyn/zen-cf-ddns#1]
Hello! And first of all I would like to thank you for the script, it is really very useful. Found it on a habr.

As I understand it, the script does not support setting the "Proxied" mode. Besides, the script, when updating the IP address, switches the record to "DNS only" mode. Because of this, the internet providers (in my case) are caching the original server address, and not the cloudflare IP address. And when the IP address is updated, there is a delay in accessing the resource.

So I'm wondering if it is possible to set "proxy mode" using a script? Something like this in the config:

`"Proxied": "true"`

**Comment by DzenDyn** [comment]
Hello! It's nice to know that the zen-cf-ddns script is useful for you. I will try to make the changes you need in the near future. Best regards.

**Comment by DzenDyn** [comment]
Hello again!
Proxied feature added to master branch. Enjoy :)
